//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 28/05/2014.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface StyleKitName : NSObject

// Drawing Methods
+ (void)drawCircularCalibratorWithFrame: (CGRect)frame minAngle: (CGFloat)minAngle maxAngle: (CGFloat)maxAngle;

@end
