//
//  SBR_StyleKitExported.h
//  Lab-VC-Transitions
//
//  Created by Chris Mitchelmore on 06/06/2014.
//  Copyright (c) 2014 Air Craft. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface SBR_StyleKitExported : NSObject

// Drawing Methods
+ (void)drawCircularCalibratorWithFrame: (CGRect)frame maximum: (CGFloat)maximum minimum: (CGFloat)minimum showExluded: (BOOL)showExluded excludeMinimum: (CGFloat)excludeMinimum excludeMaximum: (CGFloat)excludeMaximum;

@end
